name: edyon
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.0.0
  http: ^1.2.1
  shared_preferences: ^2.0.6
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  csc_picker: ^0.2.7
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/edyonicon.png"

assets:
  - assets/images/
  - assets/icon/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/PoppinsLight.ttf
        weight: 700
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400

flutter:
  uses-material-design: true
